### ISSUE TITLE
Attempted to define AOI from existing *.tf 

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/NRCS-Engineering-Tools---ArcGIS-Pro#16]
![DefineAOI_from_existing_tif](https://user-images.githubusercontent.com/63659670/109333038-8fb39980-7824-11eb-8e20-f372c89b5d54.JPG)

**Comment by CEM-NRCS** [comment]
Define AOI now contains a check for linear units for the input DEM or AOI, and if neither use a projected coordinate system, the script should exit with meaningful error messages before reaching this point.
