### ISSUE TITLE
Digitize Outlets for Drainage Area

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/NRCS-Engineering-Tools---ArcGIS-Pro#18]
Under Watershed Tools > Watershed Delineation Tools I am unable to digitize an outlet.  It will not allow me to actually digitize, it selects all the streams in the stream network.  If I have the contours highlighted in the TOC, it changes the symbology from contours to stream network and selects all the contours in the TOC, if I allow it to select the streams layer, it will allow me to digitize ONE outlet and then it gives me a drainage area on all streams in the stream network.  
![Digitize_Outlet](https://user-images.githubusercontent.com/63659670/109358610-a4565880-7849-11eb-9c14-503a6fde4ff7.JPG)

**Comment by TaraKingNRCS** [comment]
I also had this issue.  When I removed the "default" property (was set to a layer file) in the tool properties, it ran fine.
![image](https://user-images.githubusercontent.com/66689593/109517528-63438b80-7a77-11eb-8bd3-d2a4561946a9.png)

**Comment by CEM-NRCS** [comment]
Tara's solution has been adopted to the master copy and posted in early June, 2021.
