### ISSUE TITLE
Creating Stream Network 

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/NRCS-Engineering-Tools---ArcGIS-Pro#19]
Why must there be a layer input under Digitize Culverts when using the CREATE STREAM NETWORK Tool under Watershed Delineations?  It won't allow me to create a Stream Network if DIGITIZE CULVERTS is empty.  And why is it set to 5 acres instead of 1 acre, as it was in the ArcMAP version?  
![stream_network](https://user-images.githubusercontent.com/63659670/122458108-0fe94080-cf75-11eb-830e-6661e056741e.JPG)

**Comment by CEM-NRCS** [comment]
This was a bug. Code has been added where culverts can be left blank. New version of Create Stream Network to be posted on or after July 1st, 2021 will contain this change.
